import { useEffect, useRef, useState, type CSSProperties } from 'react';
import * as E from './engine';
import { GearIcon, MaterialIcon } from './Icons';
import { PhaserArena, type ArenaHandle } from './phaser/PhaserArena';
import { platformBridge } from '../platform/bridge';
import { platformConfig } from '../platform/config';
import './idle.css';
const asset=(path:string)=>`${import.meta.env.BASE_URL}${path}`;
const fmt=(v:number)=>v>=1e15?v.toExponential(2):new Intl.NumberFormat('ru-RU',{notation:v>=10000?'compact':'standard',maximumFractionDigits:v<10?1:0}).format(v);
type Panel='inventory'|'path'|'training'|'help'|null;
function load(){try{return E.normalize(JSON.parse(localStorage.getItem(E.SAVE_KEY)||'null'));}catch{return E.fresh();}}
export default function Game(){
 const [initial]=useState(load);const ref=useRef<E.State>(initial);const [s,setS]=useState({...initial});
 const [panel,setPanel]=useState<Panel>(null),[gear,setGear]=useState<E.GearId|null>(null),[bulk,setBulk]=useState(1);
 const [notice,setNotice]=useState('Нажимайте на монстра. Шлем уже добавляет автоурон.');
 const [celebrating,setCelebrating]=useState(false),[adBusy,setAdBusy]=useState(false),[hidden,setHidden]=useState(document.hidden),[started,setStarted]=useState(false);
 const [saveProblem,setSaveProblem]=useState(false);
 const [sceneReady,setSceneReady]=useState(false);
 const celebrateTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const blocked=useRef(false),saveDirty=useRef(false),arena=useRef<ArenaHandle|null>(null);
 const refresh=()=>{saveDirty.current=true;setS({...ref.current});};
 const save=()=>{try{localStorage.setItem(E.SAVE_KEY,JSON.stringify(ref.current));saveDirty.current=false;setSaveProblem(false);}catch{setSaveProblem(true);}};
 const mutate=(fn:(state:E.State)=>void)=>{fn(ref.current);refresh();save();};
 blocked.current=!started||!sceneReady||hidden||!!panel||celebrating||adBusy||s.location==='guild'||s.offerRoom!==null;
 const announce=(out:E.Outcome)=>{
  if(!out.killed&&!out.failed)return;
  if(out.failed)setNotice('Время вышло. Добыча сохранена — усильте экипировку и повторите.');
  else if(out.bossWon){setNotice(ref.current.completed?'Подземелье пройдено! Можно продолжать фарм.':'Босс повержен! Следующая комната открыта.');setCelebrating(true);celebrateTimer.current=setTimeout(()=>setCelebrating(false),1800);}
  else if(out.unlocked)setNotice('Путь открыт! Нажмите «Вглубь» или оставайтесь фармить.');
  else if(out.drop)setNotice(`Найдено: ${E.MATERIALS.find(m=>m.id===out.drop)!.name} · +${fmt(out.gold!)} золота`);
  save();
 };
 useEffect(()=>{
  const visibility=()=>{setHidden(document.hidden);save();};
  const pagehide=()=>save();
  const pause=()=>{blocked.current=true;setAdBusy(true);};
  const resume=()=>setAdBusy(false);
  document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',pagehide);
  window.addEventListener('mage:platform-pause',pause);window.addEventListener('mage:platform-resume',resume);
  const saving=setInterval(()=>{if(saveDirty.current)save();},15000);
  return()=>{clearInterval(saving);if(celebrateTimer.current)clearTimeout(celebrateTimer.current);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('pagehide',pagehide);window.removeEventListener('mage:platform-pause',pause);window.removeEventListener('mage:platform-resume',resume);};
 },[]);
 useEffect(()=>{if(sceneReady||s.location==='guild')platformBridge.loadingFinished();},[sceneReady,s.location]);
 useEffect(()=>{if(!started||!sceneReady||hidden||panel||celebrating||adBusy||s.location==='guild'||s.offerRoom!==null)platformBridge.gameplayStop();else platformBridge.gameplayStart();},[started,sceneReady,hidden,panel,celebrating,adBusy,s.location,s.offerRoom]);
 useEffect(()=>{const esc=(e:KeyboardEvent)=>{if(e.key==='Escape'){setPanel(null);setGear(null);}};window.addEventListener('keydown',esc);return()=>window.removeEventListener('keydown',esc);},[]);

 useEffect(()=>{const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const scope=document.querySelector('.start-overlay')||document.querySelector('[role="dialog"]');if(!scope)return;const list=Array.from(scope.querySelectorAll<HTMLElement>('button:not(:disabled),[tabindex="0"]'));if(!list.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&(document.activeElement===first||!scope.contains(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!scope.contains(document.activeElement))){e.preventDefault();first.focus();}};document.addEventListener('keydown',trap);return()=>document.removeEventListener('keydown',trap);},[]);
 const currentLayer=E.layer(s.room),isBoss=E.boss(s.room);
 const enemyName=isBoss?'Хранитель глубины':['Пожиратель костей','Склеповый охотник','Страж катакомб','Проклятое создание','Тварь из глубин'][(s.room+s.serial)%5];
 const openPanel=(p:Panel)=>{setGear(null);setPanel(p);};
 const next=()=>{let room=s.room+1;while(s.defeated.includes(room))room++;mutate(t=>{if(E.go(t,room))setNotice(`Комната ${room}. Путь продолжается.`);});};
 const gearButton=(id:E.GearId)=>{
  const d=E.EQUIPMENT.find(x=>x.id===id)!,g=s.gear[id],locked=s.highest<d.gate;
  const ready=!locked&&((g.level<999&&s.gold>=E.gearCost(s,id))||E.MILESTONES.some((t,i)=>g.level>=t&&!g.upgrades.includes(t)&&s.gold>=E.upgradeCost(id,i)));
  return <button key={id} className={`gear-slot ${gear===id?'selected':''} ${g.level?'owned':'unowned'} ${ready?'upgrade-ready':''}`} style={{'--gear-color':d.color} as CSSProperties} onClick={()=>{setGear(gear===id?null:id);setPanel(null);}} title={ready?(g.level?'Доступно улучшение':'Доступна покупка'):d.title} aria-label={`${d.name}, ${g.level?`уровень ${g.level}`:`открывается в комнате ${d.gate}`}`}><GearIcon id={id}/><span>{d.name}</span><small>{g.level?`ур. ${g.level}`:locked?`◈ ${d.gate}`:'Купить'}</small>{ready&&<i className="upgrade-indicator" aria-hidden="true">↑</i>}</button>;
 };
 const sellLoot=(id?:E.MaterialId,contract=false)=>mutate(t=>{const gold=E.sell(t,id,contract);setNotice(contract?`Заказ сдан: +${fmt(gold)} золота, +5 репутации`:`Продано: +${fmt(gold)} золота`);});
 async function rewarded(){if(adBusy||s.offerRoom===null)return;const room=s.offerRoom;setAdBusy(true);const success=await platformBridge.rewardedBreak();if(success)mutate(t=>{E.rescue(t,room);});else setNotice('Реклама недоступна. Награда не выдана, можно повторить босса бесплатно.');setAdBusy(false);}
 const inventoryList=(guild=false)=><div className="material-list">{E.MATERIALS.map(m=>{const stack=s.inventory[m.id];return <article key={m.id} className={!stack.count?'empty':''}><div className="material-art" style={{color:m.color}}><MaterialIcon id={m.id}/></div><div><strong>{m.name}</strong><small>{stack.count} шт. · стоимость партии <b>{fmt(stack.value)}</b></small>{guild&&stack.count>0&&<div className="trade-actions"><button onClick={()=>sellLoot(m.id)}>Продать</button><button disabled={stack.count<5} onClick={()=>sellLoot(m.id,true)}>Сдать 5 · +5 реп.</button></div>}</div></article>;})}</div>;
 return <main className="idle-shell">
  <header className="brand"><span className="brand-symbol">◈</span><div><h1>IDLE <em>DANGEROUS</em></h1><small>ХРОНИКИ ГЛУБИН</small></div><button aria-label="Помощь" onClick={()=>openPanel('help')}>?</button><button aria-label={s.sound?'Выключить звук':'Включить звук'} onClick={()=>mutate(t=>{t.sound=!t.sound;})}>{s.sound?'♪':'♩'}</button></header>
  <section className="resources" aria-label="Ресурсы"><div className="gold"><img src={asset('art/effects/coin.webp')} alt=""/><span>ЗОЛОТО</span><strong data-testid="gold">{fmt(s.gold)}</strong></div><div><span>ОБЩИЙ УРОН</span><strong>{fmt(E.totalDps(s))}<small> / сек</small></strong></div><button onClick={()=>openPanel('training')}><span>УРОН ЗА КЛИК</span><strong>{fmt(E.clickDamage(s))}<small> ＋</small></strong></button></section>
  {s.location==='dungeon'?<>
   <section className="depth-header"><div><small>ПОДЗЕМЕЛЬЕ · ЯРУС {currentLayer.region} / 6</small><h2>{currentLayer.name}</h2></div><button onClick={()=>openPanel('path')}>Путь <span>↟</span></button></section>
   <div className="room-progress"><span>Комната <b>{s.room}</b> / 105</span><div className="pips">{Array.from({length:10},(_,i)=><i key={i} className={isBoss?'boss-pip':i<s.kills?'filled':''}/>)}</div><b>{isBoss?'БОСС':`${s.kills} / 10`}</b></div>
   <section className={`arena ${isBoss?'boss-arena':''}`}>
    <PhaserArena handle={arena} bridge={{state:()=>ref.current,blocked:()=>blocked.current,changed:refresh,outcome:announce,attacked:()=>setGear(null),loading:(progress,error)=>setSceneReady(progress===1&&!error)}}/>
    <div className="enemy-caption"><small>{isBoss?'СТРАЖ ПУТИ':'ОБИТАТЕЛЬ ПОДЗЕМЕЛЬЯ'}</small><h3>{enemyName}</h3><div className="hp-track"><i style={{width:`${Math.max(0,s.hp/E.hpMax(s)*100)}%`}}/><span>{fmt(s.hp)} / {fmt(E.hpMax(s))} HP</span></div>{isBoss&&<div className={`boss-timer ${s.bossTime<10?'danger':''}`}>◷ {s.bossTime.toFixed(1)} с {s.boost?'· ×2 DPS':''}</div>}</div>
    <button className="enemy-target keyboard-attack" aria-label="Ударить монстра" onClick={()=>arena.current?.attack()} disabled={celebrating||s.offerRoom!==null}><span>Ударить · Enter / пробел</span></button>
    <div className="gear-rail left">{(['helmet','armor','bracers','boots'] as E.GearId[]).map(gearButton)}</div>
    <div className="gear-rail right">{(['shoulders','ring','amulet'] as E.GearId[]).map(gearButton)}<button className={`gear-slot focus ${s.focusUntil>Date.now()?'active':''}`} onClick={()=>{if(s.clickLevel<10)openPanel('training');else mutate(t=>{if(E.focus(t))setNotice('Боевой настрой: урон клика ×2 на 15 секунд.');});}} disabled={s.clickLevel>=10&&Date.now()<s.focusReady}><GearIcon id="click"/><span>Настрой</span><small>{s.clickLevel<10?'Клик ур. 10':Date.now()<s.focusUntil?`${Math.ceil((s.focusUntil-Date.now())/1000)} с`:Date.now()<s.focusReady?`${Math.ceil((s.focusReady-Date.now())/1000)} с`:'×2 клик'}</small></button></div>
    {!gear&&<div className="tap-hint">НАЖИМАЙТЕ НА МОНСТРА<br/><small>Экипировка атакует автоматически</small></div>}
    {celebrating&&<div className="victory-flash"><span>✦</span><h2>{s.completed?'ПОДЗЕМЕЛЬЕ ПРОЙДЕНО':'БОСС ПОВЕРЖЕН'}</h2><p>Добыча собрана · путь открыт</p></div>}
    {gear&&(()=>{const d=E.EQUIPMENT.find(x=>x.id===gear)!,g=s.gear[gear];return <aside className="gear-popover" aria-label={`Прокачка: ${d.name}`}><button className="close" aria-label="Закрыть прокачку" onClick={()=>setGear(null)}>×</button><div className="gear-title"><div style={{color:d.color}}><GearIcon id={gear}/></div><div><small>ЭКИПИРОВКА · {g.level?`УРОВЕНЬ ${g.level}`:'НЕ КУПЛЕНО'}</small><h3>{d.title}</h3><p>{fmt(E.gearDps(s,gear))} урона / сек</p></div></div>{s.highest<d.gate?<p className="unlock-rule">Откройте комнату {d.gate}, чтобы купить предмет.</p>:<><div className="buy-row"><div className="bulk">{[1,10,25,999].map(n=><button key={n} className={bulk===n?'chosen':''} onClick={()=>setBulk(n)}>{n===999?'MAX':`×${n}`}</button>)}</div><button className="gold-button" disabled={s.gold<E.gearCost(s,gear)||g.level>=999} onClick={()=>mutate(t=>{const n=E.buy(t,gear,bulk);if(n)setNotice(`${d.name}: +${n} ур.`);})}>{g.level>=999?'Макс. уровень':g.level?`Улучшить · от ${fmt(E.gearCost(s,gear))}`:`Купить · ${fmt(d.cost)}`}</button></div><div className="milestones">{E.MILESTONES.map((t,i)=><button key={t} className={g.level>=t&&!g.upgrades.includes(t)&&s.gold>=E.upgradeCost(gear,i)?'upgrade-ready':''} disabled={g.level<t||g.upgrades.includes(t)||s.gold<E.upgradeCost(gear,i)} onClick={()=>mutate(state=>{E.specialize(state,gear,t);})}><span>{g.upgrades.includes(t)?'✓':`ур. ${t}`}</span><b>×2</b><small>{g.upgrades.includes(t)?'куплено':fmt(E.upgradeCost(gear,i))}</small></button>)}</div></>}<small className="popover-hint">Нажмите на монстра, чтобы закрыть окно и ударить</small></aside>;})()}
   </section>
   <div className="notice" role="status">{notice}</div>
   <section className="advance"><button className="exit-button" onClick={()=>{setGear(null);mutate(E.leave);setNotice('Вы в гильдии. Добыча и глубина сохранены.');}}>↥ В гильдию<small>Выйти с добычей</small></button><button className="gold-button" disabled={s.room>=s.highest||s.room===104&&s.completed} onClick={next}>{s.completed&&s.room===104?'Путь завершён':'Вглубь →'}<small>{s.room<s.highest?'Следующая открытая комната':isBoss?'Победите босса':'Победите 10 монстров'}</small></button></section>
  </>:<section className="guild-screen"><div className="guild-emblem">◈</div><small>БЕЗОПАСНОЕ МЕСТО</small><h2>Гильдия искателей</h2><p>Продайте добычу или сдайте партии по 5 компонентов, чтобы заслужить репутацию.</p><div className="guild-rank"><span>{s.reputation>=100?'Мастер глубин':s.reputation>=25?'Искатель':'Новичок гильдии'}</span><b>{s.reputation} реп.</b></div><div className="loot-summary"><span>Рюкзак · {E.lootCount(s)} шт.</span><b>{fmt(E.lootValue(s))} золота</b></div>{inventoryList(true)}<button className="gold-button wide" disabled={!E.lootCount(s)} onClick={()=>sellLoot()}>Продать всю добычу · {fmt(E.lootValue(s))}</button><p className="notice">{notice}</p><button className="return-button wide" onClick={()=>{mutate(E.enter);setNotice('Вы вернулись в подземелье.');}}>Спуститься · комната {s.room} ↓</button><button className="wide subdued" onClick={()=>openPanel('path')}>Выбрать открытую комнату</button></section>}
  <nav className="bottom-nav"><button onClick={()=>{if(s.location==='guild')mutate(E.enter);setPanel(null);setGear(null);}} className={s.location==='dungeon'&&!panel?'active':''}><span>⚔</span>Подземелье</button><button onClick={()=>openPanel('inventory')}><span>▣<b>{E.lootCount(s)}</b></span>Инвентарь</button><button onClick={()=>openPanel('training')}><span>✧</span>Тренировка</button><button onClick={()=>{setPanel(null);setGear(null);mutate(E.leave);}} className={s.location==='guild'?'active':''}><span>⌂</span>Гильдия</button></nav>
  {saveProblem&&<div className="save-warning">Браузер не разрешает сохранение. Прогресс доступен до закрытия страницы.</div>}
  {panel&&<div className="modal-backdrop" onClick={()=>setPanel(null)}><section className={`modal ${panel==='path'?'path-modal':''}`} role="dialog" aria-modal="true" aria-label={{inventory:'Инвентарь',path:'Путь в глубины',training:'Тренировка',help:'Как играть'}[panel]} onClick={e=>e.stopPropagation()}><button autoFocus className="close" aria-label="Закрыть окно" onClick={()=>setPanel(null)}>×</button>
   {panel==='inventory'?<><small>ВСЯ ДОБЫЧА СОХРАНЕНА</small><h2>Инвентарь</h2><div className="loot-summary"><span>{E.lootCount(s)} компонентов</span><b>{fmt(E.lootValue(s))} золота</b></div>{inventoryList()}<p>Ценность добычи растёт с глубиной. Продажа и сдача заказов доступны в гильдии.</p><button className="gold-button wide" onClick={()=>{setPanel(null);mutate(E.leave);}}>Выйти в гильдию с добычей</button></>:panel==='training'?<><div className="training-icon"><GearIcon id="click"/></div><small>ЛИЧНАЯ СИЛА</small><h2>Тренировка удара</h2><p>Усиливает каждый ваш клик. Все предметы экипировки независимо добавляют автоматический урон.</p><div className="training-stats"><span>Уровень <b>{s.clickLevel}</b></span><span>Урон <b>{fmt(E.clickDamage(s))}</b></span></div><button className="gold-button wide" disabled={s.gold<E.clickCost(s)||s.clickLevel>=999} onClick={()=>mutate(E.train)}>Улучшить удар · {fmt(E.clickCost(s))}</button><p>Каждый уровень усиливает ручной удар. Цена растёт быстрее силы: чередуйте тренировку с улучшением экипировки.</p><div className="ability-info"><b>Боевой настрой · с уровня 10</b><p>Вдвое усиливает клики на 15 секунд. После действия восстанавливается 10 минут.</p></div></>:panel==='path'?<><small>ОДИН ДЛИННЫЙ СПУСК</small><h2>Путь в глубины</h2><p>Открыто {s.highest} / 105 комнат. Сюжетные боссы побеждаются один раз.</p><div className="path-list">{E.LAYERS.map(l=><div className="path-layer" key={l.start}><h3>{l.region}. {l.name}</h3>{Array.from({length:l.end-l.start+1},(_,i)=>l.start+i).map(room=><button key={room} className={`path-room ${room===s.room?'current':''} ${E.boss(room)?'boss-room':''} ${s.defeated.includes(room)?'defeated':''}`} disabled={room>s.highest||s.defeated.includes(room)} onClick={()=>{mutate(t=>{E.go(t,room);E.enter(t);});setPanel(null);}}><span className="node">{s.defeated.includes(room)?'✓':room>s.highest?'◇':E.boss(room)?'♜':room}</span><span>Комната {room}<small>{s.defeated.includes(room)?'Босс повержен':room>s.highest?'Путь закрыт':E.boss(room)?'Босс · 30 секунд':room===s.room?'Вы здесь':'10 монстров · фарм'}</small></span><b>{room===s.room?'◀':room<=s.highest&&!s.defeated.includes(room)?'→':''}</b></button>)}</div>)}</div></>:<><small>IDLE DANGEROUS</small><h2>Всё глубже. Всё сильнее.</h2><p>Нажимайте на врага, чтобы бить. Купленная экипировка наносит общий автоматический урон.</p><p>Нажмите на предмет сбоку: покупайте уровни и отдельные усиления ×2 на рубежах 10, 25, 50, 100 и 150.</p><p>Убейте 10 монстров и нажмите «Вглубь». Каждая пятая комната — босс на 30 секунд. После победы вы вернётесь на безопасную комнату.</p><p>Компоненты попадают в рюкзак. Выйдите в гильдию в любой момент: продайте добычу или сдайте партии по 5 за золото и репутацию.</p><p>При открытом инвентаре, пути, тренировке, в гильдии и на скрытой вкладке бой приостановлен. Окно экипировки позволяет продолжать бой.</p><button className="gold-button wide" onClick={()=>setPanel(null)}>Понятно</button></>}
  </section></div>}
  {s.offerRoom!==null&&!panel&&s.location==='dungeon'&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Попытка босса завершена"><small>КОМНАТА {s.offerRoom}</small><h2>Время вышло</h2><p>Добыча сохранена. Можно усилиться на предыдущей комнате или повторить бой.</p><button className="gold-button wide" disabled={adBusy} onClick={()=>mutate(t=>{E.go(t,t.offerRoom!);})}>Повторить · 30 секунд</button>{platformConfig.id!=='local'&&!s.rescueUsed&&<button className="return-button wide" disabled={adBusy} onClick={rewarded}>{adBusy?'Загрузка рекламы…':'Смотреть рекламу · 15 с и ×2 DPS'}</button>}<button className="wide subdued" disabled={adBusy} onClick={()=>mutate(t=>{t.offerRoom=null;})}>Вернуться к фарму · комната {s.room}</button><button className="wide subdued" disabled={adBusy} onClick={()=>mutate(E.leave)}>Выйти в гильдию</button></section></div>}
  {!started&&<div className="start-overlay"><div className="start-rune">◈</div><small>СПУСК НАЧИНАЕТСЯ</small><h2>IDLE<br/><em>DANGEROUS</em></h2><p>Собирайте трофеи. Усиливайте экипировку.<br/>Узнайте, что скрывается в глубине.</p><button className="gold-button" onClick={()=>setStarted(true)}>{s.totalKills?'Продолжить спуск':'Войти в подземелье'}</button><small>105 комнат · 7 предметов · одна Бездна</small></div>}
 </main>;
}
